name: Test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  UIPATHCLI: "${{ github.workspace }}\\.uipath-cli\\uipcli.exe"
  ORCH_FOLDER: 'Shared/deployment-artifact'
  FOLDER_NAME:  'deployment-artifact'
  PACKAGE: "package pack ${{ github.workspace }}\\project.json -o ${{ github.workspace }}\\package  -l en-US --libraryOrchestratorApplicationId ${{secrets.ORCH_OAUTH_CLIENT_ID}} --libraryOrchestratorApplicationSecret '${{secrets.ORCH_CLIENT_SECRET}}' --libraryOrchestratorApplicationScope '${{secrets.ORCH_OAUTH_CLIENT_Scopes}}' --libraryOrchestratorUrl ${{secrets.ORCH_URL}} --libraryOrchestratorTenant ${{secrets.ORCH_TENANT_NAME}} --libraryOrchestratorAccountForApp ${{secrets.ORCH_ACCOUNT_NAME}}"
  DEPLOY: "package deploy ${{ github.workspace }}\\package ${{secrets.ORCH_URL}} ${{secrets.ORCH_TENANT_NAME}} -I ${{secrets.ORCH_OAUTH_CLIENT_ID}} -S '${{secrets.ORCH_CLIENT_SECRET}}' --applicationScope '${{secrets.ORCH_OAUTH_CLIENT_SCOPES}}' -A ${{secrets.ORCH_ACCOUNT_NAME}}"
  
jobs:
  build-and-deploy-package:
    runs-on: [windows-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: 'develop'
        
      - name: Read Version
        id: read_version
        run: |
                $version = Get-Content "${{ github.workspace }}\release_versions\version.yml" | Select-String -Pattern "version:" | ForEach-Object { $_ -replace 'version:/s*', '' }
                Write-Output "Version_current: $version"
                echo "::set-output name=version::$version"
        shell: PowerShell
        
      - name: Increment Version
        id: increment_version
        run: |
                # Increment the version
                $current_version = $env:INPUT_VERSION
                # $version_parts = $current_version -split '\.'
                # $incremented_version = "{0}.{1}.{2}" -f $version_parts[0], $version_parts[1], ($version_parts[2] + 1)
                $incremented_version = $current_version -split'\.'
                $incremented_version[-1] = [int]$incremented_version[-1]+1
                $incremented_version = $incremented_version -join'.'
                Write-Output "Incremented Version: $incremented_version"
                echo "::set-output name=incremented_version::$incremented_version"
        env:
          INPUT_VERSION: ${{ steps.read_version.outputs.version }}
        shell: PowerShell

  
      - name: Build Package
        run: |
                 $incremented_version = $env:INPUT_VERSION
                 $build_version = $incremented_version -split'\:'
                 $build_version = $build_version[-1]
                 Write-Output "Build Version: $build_version"
                 Invoke-Expression "${{ env.UIPATHCLI }} ${{ env.PACKAGE }} --version $build_version --libraryOrchestratorFolder ${{env.ORCH_FOLDER}}"
                 ls package
        env:
          INPUT_VERSION: ${{ steps.increment_version.outputs.incremented_version }}
        shell: PowerShell



      - name: Test UiPath Authentication
        run: |
               & $env:UIPATHCLI package list -A $env:APP_ID -S $env:APP_SECRET --applicationScope $env:SCOPE --orchestratorUrl $env:ORCH_URL --tenant $env:TENANT --accountForApp $env:ACCOUNT
        env:
          APP_ID: ${{ secrets.UIPATH_APP_ID }}
          APP_SECRET: ${{ secrets.UIPATH_APP_SECRET }}
          SCOPE: ${{ secrets.UIPATH_SCOPE }}
          ORCH_URL: ${{ secrets.UIPATH_URL }}
          TENANT: ${{ secrets.UIPATH_TENANT }}
          ACCOUNT: ${{ secrets.UIPATH_ACCOUNT }}


      - name: Deploy Package                                                                                                                                                                                        
        run: |
                Invoke-Expression "${{ env.UIPATHCLI }} ${{env.DEPLOY}} -o ${{env.ORCH_FOLDER}}" 
        # continue-on-error: true

     